# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NDg3NmU1YzQ0ODdkY2NhMmFlZTkwNTI5ZTczZWMyMDU1NTFiMmYyMzI1MzZmYmQ4NDY0NDNkOTBiMjc1YjcyOTEyMzFhYWUxMzJjOTg0MTUxNzc3MjAwYWE5OTM5OTVjMWNjZmVlNTE0ZTQwOWY3Y2FjMTM3NTEzZWJjZjI5MTQ=
