package sn.samabutik.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AppSettingsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSettingsAllPropertiesEquals(AppSettings expected, AppSettings actual) {
        assertAppSettingsAutoGeneratedPropertiesEquals(expected, actual);
        assertAppSettingsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSettingsAllUpdatablePropertiesEquals(AppSettings expected, AppSettings actual) {
        assertAppSettingsUpdatableFieldsEquals(expected, actual);
        assertAppSettingsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSettingsAutoGeneratedPropertiesEquals(AppSettings expected, AppSettings actual) {
        assertThat(actual)
            .as("Verify AppSettings auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSettingsUpdatableFieldsEquals(AppSettings expected, AppSettings actual) {
        assertThat(actual)
            .as("Verify AppSettings relevant properties")
            .satisfies(a -> assertThat(a.getParamKey()).as("check paramKey").isEqualTo(expected.getParamKey()))
            .satisfies(a -> assertThat(a.getParamValue()).as("check paramValue").isEqualTo(expected.getParamValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAppSettingsUpdatableRelationshipsEquals(AppSettings expected, AppSettings actual) {
        // empty method
    }
}
