package sn.samabutik.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAllPropertiesEquals(Media expected, Media actual) {
        assertMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAllUpdatablePropertiesEquals(Media expected, Media actual) {
        assertMediaUpdatableFieldsEquals(expected, actual);
        assertMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaAutoGeneratedPropertiesEquals(Media expected, Media actual) {
        assertThat(actual)
            .as("Verify Media auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaUpdatableFieldsEquals(Media expected, Media actual) {
        assertThat(actual)
            .as("Verify Media relevant properties")
            .satisfies(a -> assertThat(a.getUrl()).as("check url").isEqualTo(expected.getUrl()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getFormat()).as("check format").isEqualTo(expected.getFormat()))
            .satisfies(a -> assertThat(a.getSizeBytes()).as("check sizeBytes").isEqualTo(expected.getSizeBytes()))
            .satisfies(a -> assertThat(a.getWidth()).as("check width").isEqualTo(expected.getWidth()))
            .satisfies(a -> assertThat(a.getHeight()).as("check height").isEqualTo(expected.getHeight()))
            .satisfies(a -> assertThat(a.getDurationSec()).as("check durationSec").isEqualTo(expected.getDurationSec()))
            .satisfies(a -> assertThat(a.getIsMain()).as("check isMain").isEqualTo(expected.getIsMain()))
            .satisfies(a -> assertThat(a.getDisplayOrder()).as("check displayOrder").isEqualTo(expected.getDisplayOrder()))
            .satisfies(a -> assertThat(a.getAltText()).as("check altText").isEqualTo(expected.getAltText()))
            .satisfies(a -> assertThat(a.getUploadedAt()).as("check uploadedAt").isEqualTo(expected.getUploadedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMediaUpdatableRelationshipsEquals(Media expected, Media actual) {
        assertThat(actual)
            .as("Verify Media relationships")
            .satisfies(a -> assertThat(a.getProductGallery()).as("check productGallery").isEqualTo(expected.getProductGallery()))
            .satisfies(a -> assertThat(a.getPackGallery()).as("check packGallery").isEqualTo(expected.getPackGallery()));
    }
}
