package sn.samabutik.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.samabutik.domain.AssertUtils.bigDecimalCompareTo;

public class PackAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackAllPropertiesEquals(Pack expected, Pack actual) {
        assertPackAutoGeneratedPropertiesEquals(expected, actual);
        assertPackAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackAllUpdatablePropertiesEquals(Pack expected, Pack actual) {
        assertPackUpdatableFieldsEquals(expected, actual);
        assertPackUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackAutoGeneratedPropertiesEquals(Pack expected, Pack actual) {
        assertThat(actual)
            .as("Verify Pack auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackUpdatableFieldsEquals(Pack expected, Pack actual) {
        assertThat(actual)
            .as("Verify Pack relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getDiscountType()).as("check discountType").isEqualTo(expected.getDiscountType()))
            .satisfies(a ->
                assertThat(a.getDiscountValue())
                    .as("check discountValue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDiscountValue())
            )
            .satisfies(a -> assertThat(a.getStartDate()).as("check startDate").isEqualTo(expected.getStartDate()))
            .satisfies(a -> assertThat(a.getEndDate()).as("check endDate").isEqualTo(expected.getEndDate()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getDisplayOnHomepage()).as("check displayOnHomepage").isEqualTo(expected.getDisplayOnHomepage()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackUpdatableRelationshipsEquals(Pack expected, Pack actual) {
        assertThat(actual)
            .as("Verify Pack relationships")
            .satisfies(a -> assertThat(a.getMainMedia()).as("check mainMedia").isEqualTo(expected.getMainMedia()));
    }
}
