package sn.samabutik.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PackItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackItemAllPropertiesEquals(PackItem expected, PackItem actual) {
        assertPackItemAutoGeneratedPropertiesEquals(expected, actual);
        assertPackItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackItemAllUpdatablePropertiesEquals(PackItem expected, PackItem actual) {
        assertPackItemUpdatableFieldsEquals(expected, actual);
        assertPackItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackItemAutoGeneratedPropertiesEquals(PackItem expected, PackItem actual) {
        assertThat(actual)
            .as("Verify PackItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackItemUpdatableFieldsEquals(PackItem expected, PackItem actual) {
        assertThat(actual)
            .as("Verify PackItem relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPackItemUpdatableRelationshipsEquals(PackItem expected, PackItem actual) {
        assertThat(actual)
            .as("Verify PackItem relationships")
            .satisfies(a -> assertThat(a.getPack()).as("check pack").isEqualTo(expected.getPack()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
