package sn.samabutik.domain;

import static org.assertj.core.api.Assertions.assertThat;
import static sn.samabutik.domain.AssertUtils.bigDecimalCompareTo;

public class PaymentTransactionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentTransactionAllPropertiesEquals(PaymentTransaction expected, PaymentTransaction actual) {
        assertPaymentTransactionAutoGeneratedPropertiesEquals(expected, actual);
        assertPaymentTransactionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentTransactionAllUpdatablePropertiesEquals(PaymentTransaction expected, PaymentTransaction actual) {
        assertPaymentTransactionUpdatableFieldsEquals(expected, actual);
        assertPaymentTransactionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentTransactionAutoGeneratedPropertiesEquals(PaymentTransaction expected, PaymentTransaction actual) {
        assertThat(actual)
            .as("Verify PaymentTransaction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentTransactionUpdatableFieldsEquals(PaymentTransaction expected, PaymentTransaction actual) {
        assertThat(actual)
            .as("Verify PaymentTransaction relevant properties")
            .satisfies(a -> assertThat(a.getProvider()).as("check provider").isEqualTo(expected.getProvider()))
            .satisfies(a -> assertThat(a.getTransactionId()).as("check transactionId").isEqualTo(expected.getTransactionId()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getWebhookPayload()).as("check webhookPayload").isEqualTo(expected.getWebhookPayload()))
            .satisfies(a -> assertThat(a.getProcessedAt()).as("check processedAt").isEqualTo(expected.getProcessedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPaymentTransactionUpdatableRelationshipsEquals(PaymentTransaction expected, PaymentTransaction actual) {
        assertThat(actual)
            .as("Verify PaymentTransaction relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()));
    }
}
