package sn.samabutik.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StockMovementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementAllPropertiesEquals(StockMovement expected, StockMovement actual) {
        assertStockMovementAutoGeneratedPropertiesEquals(expected, actual);
        assertStockMovementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementAllUpdatablePropertiesEquals(StockMovement expected, StockMovement actual) {
        assertStockMovementUpdatableFieldsEquals(expected, actual);
        assertStockMovementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementAutoGeneratedPropertiesEquals(StockMovement expected, StockMovement actual) {
        assertThat(actual)
            .as("Verify StockMovement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementUpdatableFieldsEquals(StockMovement expected, StockMovement actual) {
        assertThat(actual)
            .as("Verify StockMovement relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStockMovementUpdatableRelationshipsEquals(StockMovement expected, StockMovement actual) {
        assertThat(actual)
            .as("Verify StockMovement relationships")
            .satisfies(a -> assertThat(a.getPerformedBy()).as("check performedBy").isEqualTo(expected.getPerformedBy()))
            .satisfies(a -> assertThat(a.getProduct()).as("check product").isEqualTo(expected.getProduct()));
    }
}
