package sn.samabutik.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class UserStaffAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStaffAllPropertiesEquals(UserStaff expected, UserStaff actual) {
        assertUserStaffAutoGeneratedPropertiesEquals(expected, actual);
        assertUserStaffAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStaffAllUpdatablePropertiesEquals(UserStaff expected, UserStaff actual) {
        assertUserStaffUpdatableFieldsEquals(expected, actual);
        assertUserStaffUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStaffAutoGeneratedPropertiesEquals(UserStaff expected, UserStaff actual) {
        assertThat(actual)
            .as("Verify UserStaff auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStaffUpdatableFieldsEquals(UserStaff expected, UserStaff actual) {
        assertThat(actual)
            .as("Verify UserStaff relevant properties")
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getPhone()).as("check phone").isEqualTo(expected.getPhone()))
            .satisfies(a -> assertThat(a.getPasswordHash()).as("check passwordHash").isEqualTo(expected.getPasswordHash()))
            .satisfies(a -> assertThat(a.getRole()).as("check role").isEqualTo(expected.getRole()))
            .satisfies(a -> assertThat(a.getIsActive()).as("check isActive").isEqualTo(expected.getIsActive()))
            .satisfies(a -> assertThat(a.getLastLoginAt()).as("check lastLoginAt").isEqualTo(expected.getLastLoginAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStaffUpdatableRelationshipsEquals(UserStaff expected, UserStaff actual) {
        // empty method
    }
}
